-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 13:36:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PCP_BARTEN
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PCP_BARTEN
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PCP_BARTEN` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema padariaead
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema padariaead
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `padariaead` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `PCP_BARTEN` ;

-- -----------------------------------------------------
-- Table `PCP_BARTEN`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCP_BARTEN`.`usuarios` (
  `idusuarios` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `telefone` VARCHAR(20) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCP_BARTEN`.`Ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCP_BARTEN`.`Ingredientes` (
  `idIngredientes` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `quantidade` DECIMAL(8,2) NULL,
  `unidade_medida` VARCHAR(10) NULL,
  `valor_unitario` DECIMAL(8,2) NULL,
  PRIMARY KEY (`idIngredientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCP_BARTEN`.`tipo_cerveja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCP_BARTEN`.`tipo_cerveja` (
  `idTipo_cerveja` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `info_volume` DECIMAL(8,2) NULL,
  `info_abv` DECIMAL(8,2) NULL,
  `info_amargor` DECIMAL(8,2) NULL,
  `info_cor` DECIMAL(8,2) NULL,
  `desc_mostura` VARCHAR(1000) NULL,
  `desc_lavagem` VARCHAR(1000) NULL,
  `desc_fervura` VARCHAR(1000) NULL,
  `desc_fermentacao` VARCHAR(1000) NULL,
  `OG_Estimado` DECIMAL(8,4) NULL,
  `FG_Estimado` DECIMAL(8,4) NULL,
  `tempo_fermentacao` INT NULL,
  `tempo_maturacao` INT NULL,
  PRIMARY KEY (`idTipo_cerveja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCP_BARTEN`.`Receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCP_BARTEN`.`Receita` (
  `idTipo_cerveja` INT NOT NULL,
  `idIngredientes` INT NOT NULL,
  `Quantidade` DECIMAL(8,2) NULL,
  `unidade_medida` VARCHAR(10) NULL,
  `valor_total` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo_cerveja`, `idIngredientes`),
  INDEX `fk_Receita_has_Estoque_ingredientes_Estoque_ingredientes1_idx` (`idIngredientes` ASC) VISIBLE,
  INDEX `fk_Receita_has_Estoque_ingredientes_Receita_idx` (`idTipo_cerveja` ASC) VISIBLE,
  CONSTRAINT `fk_Receita_has_Estoque_ingredientes_Receita`
    FOREIGN KEY (`idTipo_cerveja`)
    REFERENCES `PCP_BARTEN`.`tipo_cerveja` (`idTipo_cerveja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receita_has_Estoque_ingredientes_Estoque_ingredientes1`
    FOREIGN KEY (`idIngredientes`)
    REFERENCES `PCP_BARTEN`.`Ingredientes` (`idIngredientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCP_BARTEN`.`lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCP_BARTEN`.`lote` (
  `idLote` INT NOT NULL,
  `OG_prod` DECIMAL(8,4) NULL,
  `FG_prod` DECIMAL(8,4) NULL,
  `lote` VARCHAR(45) NULL,
  `data_prod` DATE NULL,
  `rendimento(L)` INT NULL,
  `data_final_fermentacao` DATETIME NULL,
  `data_final_maturacao` DATETIME NULL,
  `idTipo_cerveja` INT NOT NULL,
  PRIMARY KEY (`idLote`, `idTipo_cerveja`),
  INDEX `fk_lote_tipo_cerveja1_idx` (`idTipo_cerveja` ASC) VISIBLE,
  CONSTRAINT `fk_lote_tipo_cerveja1`
    FOREIGN KEY (`idTipo_cerveja`)
    REFERENCES `PCP_BARTEN`.`tipo_cerveja` (`idTipo_cerveja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCP_BARTEN`.`produto_acabado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCP_BARTEN`.`produto_acabado` (
  `idproduto_acabado` INT NOT NULL,
  `tipo_embalagem` VARCHAR(45) NULL,
  `quantidade` INT NULL,
  `idLote` INT NOT NULL,
  PRIMARY KEY (`idproduto_acabado`, `idLote`),
  INDEX `fk_produto_acabado_lote1_idx` (`idLote` ASC) VISIBLE,
  CONSTRAINT `fk_produto_acabado_lote1`
    FOREIGN KEY (`idLote`)
    REFERENCES `PCP_BARTEN`.`lote` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCP_BARTEN`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCP_BARTEN`.`inventario` (
  `idinventario` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `quantidade` INT NULL,
  `valor` DECIMAL(8,2) NULL,
  PRIMARY KEY (`idinventario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCP_BARTEN`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCP_BARTEN`.`pedidos` (
  `idpedidos` INT NOT NULL,
  `Cliente` VARCHAR(45) NULL,
  `Produto` VARCHAR(45) NULL,
  `Quantidade` INT NULL,
  `Data_pedido` DATETIME NULL,
  `Data_entrega` DATETIME NULL,
  PRIMARY KEY (`idpedidos`))
ENGINE = InnoDB;

USE `padariaead` ;

-- -----------------------------------------------------
-- Table `padariaead`.`cozinheiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padariaead`.`cozinheiro` (
  `idCozinheiro` INT NOT NULL,
  `Nome` VARCHAR(40) NULL DEFAULT NULL,
  `Sexo` CHAR(1) NULL DEFAULT NULL,
  `Salario` DECIMAL(8,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idCozinheiro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `padariaead`.`ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padariaead`.`ingredientes` (
  `idIngredientes` INT NOT NULL,
  `Nome` VARCHAR(40) NULL DEFAULT NULL,
  `QtdeEstoque` DECIMAL(8,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idIngredientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `padariaead`.`prato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padariaead`.`prato` (
  `idPrato` INT NOT NULL,
  `idCozinheiro` INT NOT NULL,
  `Nome` VARCHAR(40) NULL DEFAULT NULL,
  `Preco` DECIMAL(8,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idPrato`),
  INDEX `Prato_FKIndex1` (`idCozinheiro` ASC) VISIBLE,
  CONSTRAINT `prato_ibfk_1`
    FOREIGN KEY (`idCozinheiro`)
    REFERENCES `padariaead`.`cozinheiro` (`idCozinheiro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `padariaead`.`receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padariaead`.`receita` (
  `idPrato` INT NOT NULL,
  `idIngredientes` INT NOT NULL,
  PRIMARY KEY (`idPrato`, `idIngredientes`),
  INDEX `Receita_FKIndex1` (`idPrato` ASC) VISIBLE,
  INDEX `Receita_FKIndex2` (`idIngredientes` ASC) VISIBLE,
  CONSTRAINT `receita_ibfk_1`
    FOREIGN KEY (`idPrato`)
    REFERENCES `padariaead`.`prato` (`idPrato`),
  CONSTRAINT `receita_ibfk_2`
    FOREIGN KEY (`idIngredientes`)
    REFERENCES `padariaead`.`ingredientes` (`idIngredientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
ingredientes



-- Insert de dados

-- Usuários

insert into usuarios values (1,'Carlos Benjamim', 'carlosbarten@gmail.com',35999057700, 'password');
insert into usuarios values (2,'Tiago Nigro', 'primorico@gmail.com',119998778956, 'password2');
insert into usuarios values (3,'Paula Fernandes', 'passarodefogo@gmail.com',7123569898, 'password3');
insert into usuarios values (4,'Tim Maia', 'lemeaopontal@gmail.com',1578784554, 'password4');
insert into usuarios values (5,'Pe DrO Sam Pai O', 'dancarina@gmail.com',1112124545, 'password5');

select * from usuarios;

-- ---------------------------------------------------------------------

-- Inventário

insert into inventario values(1,'Tacho','Producao',2,1254.65);
insert into inventario values(2,'Barril','Producao',8,500.00);
insert into inventario values(3,'Mesa','Producao',2,100.25);
insert into inventario values(4,'Chopeira','Venda',3,3000.12);
insert into inventario values(5,'Cilindro CO2','Venda',3,550.85);

select * from inventario;

-- ----------------------------------------------------------------------

-- Tipo Receita
insert into tipo_cerveja values(1,'Premium Lager',20,4.8,15.8,4.9,'Saccharification: Adicionar 17.04 L de água a 68.9 C 64.4 C 60 min','1o Após o Mash Out, esgotar todo a mistura','Hallertauer Mittelfrueh [3.60 %] - Fervura 60.0 min','2.0 pkg Saflager Lager W-34/70 (DCL/Fermentis',1.045,1.008,10,10);
insert into tipo_cerveja values(2,'IPA Citra',50,5.8,19.8,5.9,'Saccharification: Adicionar 25.04 L de água a 68.9 C 64.4 C 60 min','1o Após o Mash Out, esgotar todo a mistura','Citra [3.60 %] - Fervura 60.0 min','2.0 pkg US-05',1.055,1.011,7,15);

select * from tipo_cerveja;

-- ----------------------------------------------------------------------

-- Ingredientes

insert into ingredientes values(1,'Malte Pilsen',250,'Kg',9.99);
insert into ingredientes values(2,'Malte Vienna',50,'Kg',19.59);
insert into ingredientes values(3,'Malte Munique',59,'Kg',21.99);
insert into ingredientes values(4,'Lupulo MittelFrueh',0.8,'Kg',59.99);
insert into ingredientes values(5,'Fermento Lager',500,'g',99.99);
insert into ingredientes values(6,'Malte IPA 1',140,'Kg',7.99);
insert into ingredientes values(7,'Malte IPA 2',78,'Kg',23.95);
insert into ingredientes values(8,'Lupulo Citra',20,'g',69.99);
insert into ingredientes values(9,'Lupulo Cascade',20,'Kg',2.99);
insert into ingredientes values(10,'Fermento US05',2,'Kg',39.99);


select* from ingredientes;

-- ---------------------------------------------------------------------

-- Receita

-- Lager
insert into receita values (1,1,4.0,'Kg',51.66);
insert into receita values (1,3,0.7,'Kg',32.66);
insert into receita values (1,4,50,'g',88.00);
insert into receita values (1,5,100,'g',99.66);
-- Ipa
insert into receita values (2,1,9.0,'Kg',78.66);
insert into receita values (2,6,0.7,'Kg',32.66);
insert into receita values (2,7,0.9,'Kg',58.00);
insert into receita values (2,8,200,'g',129.66);
insert into receita values (2,10,100,'g',120.66);

select* from receita;

-- ------------------------------------------------------------

-- Lote

insert into lote values (1,1.039,1.012,'L12',20230302,50,20230312,20230412,1);
insert into lote values (2,1.040,null,'L13',20230302,50,null,null,1);

select* from lote;

-- -------------------------------------------------------------

-- Produto acabado



